$(document).ready(function(){
		$('#slide-slick').slick({
			autoplay:true,
			autoplaySpeed:4000,
			slidesToShow:1,
			slidesToScroll:1,
			arrows:false,
			infinite:true,
			dots:false,
			speed:1500,
			fade:true,
		});
	});